// <auto-generated />
using System;
using BackendGenerators.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendGenerators.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackendGenerators.Models.Medico", b =>
                {
                    b.Property<int>("Cod_Medico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cod_Medico"));

                    b.Property<int>("CRM")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Pessoa")
                        .HasColumnType("int");

                    b.HasKey("Cod_Medico");

                    b.HasIndex("Cod_Pessoa")
                        .IsUnique();

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("BackendGenerators.Models.OrdemServicoCaixa", b =>
                {
                    b.Property<int>("Cod_OrdemServicocaixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cod_OrdemServicocaixa"));

                    b.Property<int>("Cod_Classificacao")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Laboratorio")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Pessoa")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Receita")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Servico")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Transacao")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Vendedor")
                        .HasColumnType("int");

                    b.Property<int>("Cod_armacao")
                        .HasColumnType("int");

                    b.Property<int>("Cod_lenteOD")
                        .HasColumnType("int");

                    b.Property<int>("Cod_lenteOE")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEncerramento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPrevisaoFornecedor")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumeroOrdemServico")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeServico")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.Property<double>("ValorAcrescimo")
                        .HasColumnType("double");

                    b.Property<double>("ValorDesconto")
                        .HasColumnType("double");

                    b.Property<double>("ValorUnitario")
                        .HasColumnType("double");

                    b.HasKey("Cod_OrdemServicocaixa");

                    b.ToTable("OrdemServicoCaixa");
                });

            modelBuilder.Entity("BackendGenerators.Models.Pessoa", b =>
                {
                    b.Property<int>("Cod_Pessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cod_Pessoa"));

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext");

                    b.Property<string>("Celular2")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Cnpj")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<int>("Identificador")
                        .HasColumnType("int");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("longtext");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Razaosocial")
                        .HasColumnType("longtext");

                    b.Property<bool>("Sexo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoCNPJ")
                        .HasColumnType("int");

                    b.HasKey("Cod_Pessoa");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("BackendGenerators.Models.Receita", b =>
                {
                    b.Property<int>("Cod_Receita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cod_Receita"));

                    b.Property<decimal>("AdicaoOD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AdicaoOE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("COOD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("COOE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Cod_Medico")
                        .HasColumnType("int");

                    b.Property<int>("Cod_OrdemServicocaixa")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Pessoa")
                        .HasColumnType("int");

                    b.Property<int>("Cod_Vendedor")
                        .HasColumnType("int");

                    b.Property<decimal>("DNPOD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DNPOE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DataAviamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPrescricao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LenteOD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LenteOE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("cilindricoOD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("cilindricoOE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("eixoOD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("eixoOE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("esfericoOD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("esfericoOE")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Cod_Receita");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("BackendGenerators.Models.Medico", b =>
                {
                    b.HasOne("BackendGenerators.Models.Pessoa", "Pessoa")
                        .WithOne("Medico")
                        .HasForeignKey("BackendGenerators.Models.Medico", "Cod_Pessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("BackendGenerators.Models.Pessoa", b =>
                {
                    b.Navigation("Medico");
                });
#pragma warning restore 612, 618
        }
    }
}
